channels:
  - defaults
dependencies:
  - pip
  - pip:
    - h5py==3.8.0
    - matplotlib==3.7.2
    - numpy==1.26.4
    - pytorch_lightning==1.9.0
    - scikit_learn==1.3.2
    - scipy==1.13.0
    - segmentation_models_pytorch==0.3.3
    - torch==2.2.1
    - torchmetrics==1.2.0
    - torchvision==0.17.1
    - transformers==4.38.1
    - xgboost==2.0.3
